### ISSUE TITLE
[FEED] Port should be included in activation handler

### ISSUE THREAD

**Issue by cf-sewe** [tribe29/ansible-collection-tribe29.checkmk#268]
Connecting to a checkmk server directly on a custom port (e.g. 5000) currently does not work in all cases.

Current:

https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/9c4cc6dc34c3cab31409955a8374a05d92b1d62b/roles/agent/handlers/main.yml#L5

Should be: 
```yaml
server_url: "{{ checkmk_agent_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_port }}/"
```

**Comment by robin-tribe29** [comment]
I think it makes sense to implement this, I just have a word of warning first: You mention port 5000, which would be the default port of the first Checkmk instance's Apache on a server. I advise against connecting directly, as that might have undesired side effects. You should always use the system Apache to access the site.

But I understand the overall requirement to define a port, as even the system Apache or a reverse proxy might be listening on a different port.

If you are up to the task, we appreciate your pull request. Otherwise, we will give others an opportunity to implement this.
Eventually I will implement it, when I find the time.

**Comment by cf-sewe** [comment]
> I advise against connecting directly, as that might have undesired side effects.

Thank you for your feedback and advice!
To add some background info: I am using it only for the internal communication. 
CheckMK is running in docker, and the agents communciate with the server over a private network directly with the CheckMK container.  External traefik is routed through nginx. For agent communication I am using TLS.

I hope this is a somewhat reasonable scenario.
