### ISSUE TITLE
[BUG] checkmk_agent_folder does not support folders containing dots 

### ISSUE THREAD

**Issue by Fabian-C** [tribe29/ansible-collection-tribe29.checkmk#311]
**Describe the bug**
The "Checkmk_agent_folder" variable for the agent registration does not support path containing dots

**Checkmk Version**
2.2.0p2 (CRE)

**Collection Version**
0.19.0

**Environment**
Ubuntu LXC 

**Expected behavior**
checkmk_agent_folder: "/test.com/ansible_Managed_Infrastructur/"

**Actual behavior**
msg: 'Error calling API. HTTP code 400. Details: b''{"title": "Bad Request", "status": 400, "detail": "These fields have problems: folder", "fields": {"folder": ["The folder \"/test.com/ansible_Managed_Infrastructur/"' could not be found."]}}'', ')

**Edit:**
The problem also applies to folders containing underscores _  and possibly other special characters.

**Comment by robin-checkmk** [comment]
Hi @Fabian-C,

I checked your report and I have to say: This is not a bug in the collection.

Dots are not supported in Checkmk folder paths at all.
If you create a folder with a dot in the UI, the folder name in the file system will contain `_` instead of `.`.
The REST API also states, that the folder path needs to meet this regex: `^[-\w]*$`.
In the `name` field  they are supported, if you really need them, as your example suggests.

I will add a hint to the module documentation.
